repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: debug-statements
    - id: name-tests-test
      args: ['--django']
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
    - id: reorder-python-imports
