name: Black formatter check

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
      with:
        args: --check --target-version py37 --line-length 120 --skip-string-normalization main.py
